# Generated by Django 5.1.4 on 2025-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg_app', '0002_alter_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='chicken_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
